### ISSUE TITLE
Match prettier's behavior for quoting

### ISSUE THREAD

**Issue by harigopal** [bodhish/pupilfirst-translator-vscode-ext#2]
Related to #1.

Here's a key-value pair that Prettier and this translator extension will fight over:

```yaml
# Extension output
message: "This is a reminder for \"%{title}\" event"

# Prettier's output
message: 'This is a reminder for "%{title}" event'
```

I think Prettier's behavior makes more sense.
